### ISSUE TITLE
Build failed - no method named `modified` found

### ISSUE THREAD

**Issue by razvan-panda** [JakubAdamBukaj/cargo-ls#1]
Compiling advapi32-sys v0.1.0
       Compiling kernel32-sys v0.1.0
       Compiling glob v0.2.10
       Compiling regex v0.1.30
       Compiling gcc v0.3.5
       Compiling semver v0.1.19
       Compiling threadpool v0.1.4
       Compiling strsim v0.3.0
       Compiling matches v0.1.2
       Compiling libc v0.1.6
       Compiling tar v0.2.10
       Compiling bitflags v0.1.1
       Compiling pkg-config v0.3.3
       Compiling rustc-serialize v0.3.14
    c:/Users/Razvan\.cargo\registry\src\github.com-0a35038f75765ae4\tar-0.2.10\src\lib.rs:308:56: 308:66 error: no method named `modified` found for type `std::fs::Metadata` in the current scope
    c:/Users/Razvan\.cargo\registry\src\github.com-0a35038f75765ae4\tar-0.2.10\src\lib.rs:308         octal(&mut header.mtime, relative_to_1970(stat.modified() / 1000));

                                              ^~~~~~~~~~
    error: aborting due to previous error
       Compiling winapi v0.1.17
       Compiling log v0.3.1
    Build failed, waiting for other jobs to finish...
    Could not compile `tar`.

**Comment by JakubAdamBukaj** [comment]
Can you try again? I think it's fixed now.

**Comment by razvan-panda** [comment]
This error seems to be fixed, but it is still failing to build cause of a dependency:

    $ cargo build --release
     Downloading pkg-config v0.3.5
     Downloading curl v0.2.10
     Downloading filetime v0.1.4
     Downloading term v0.2.9
     Downloading libssh2-sys v0.1.26
     Downloading miniz-sys v0.1.5
     Downloading advapi32-sys v0.1.1
     Downloading libgit2-sys v0.2.18
       Compiling strsim v0.3.0
       Compiling gcc v0.3.8
       Compiling threadpool v0.1.4
       Compiling filetime v0.1.4
       Compiling regex-syntax v0.1.2
       Compiling matches v0.1.2
       Compiling bitflags v0.1.1
       Compiling pkg-config v0.3.5
       Compiling winapi-build v0.1.0
       Compiling libc v0.1.8
       Compiling semver v0.1.19
       Compiling glob v0.2.10
       Compiling rustc-serialize v0.3.15
       Compiling winapi v0.1.23
       Compiling tar v0.2.14
       Compiling log v0.3.1
       Compiling num_cpus v0.2.6
       Compiling memchr v0.1.3
       Compiling kernel32-sys v0.1.2
       Compiling advapi32-sys v0.1.1
       Compiling libz-sys v0.1.6
       Compiling libssh2-sys v0.1.26
       Compiling libgit2-sys v0.2.18
       Compiling curl-sys v0.1.24
       Compiling aho-corasick v0.2.1
       Compiling miniz-sys v0.1.5
    Build failed, waiting for other jobs to finish...
    failed to run custom build command for `libssh2-sys v0.1.26`
    Process didn't exit successfully: `D:\Forks\cargo-ls\target\release\build\libssh2-sys-197403f26ef746c2\build-script-build` (exit code: 101)
    --- stdout
    running: "make" "-fGNUmakefile" "WITH_WINCNG=1" "WITH_ZLIB=1" "lib"

    --- stderr
    thread '<main>' panicked at '
    cmd.status() failed with The system cannot find the file specified.
     (os error 2)
    ', c:/Users/Razvan\.cargo\registry\src\github.com-0a35038f75765ae4\libssh2-sys-0.1.26\build.rs:159

**Comment by JakubAdamBukaj** [comment]
You're running into https://github.com/alexcrichton/ssh2-rs/issues/14. I won't be of much help in this regard, sorry.
